version: "3.8"
services:
  frontend:
    build:
      context: .
      target: production
    image: exp36_stage-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/certs:/etc/nginx/certs:ro
